/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SheetsSyncRouteImport } from './routes/sheets-sync'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResumeVaultRouteImport } from './routes/resume-vault'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as EmailOutreachRouteImport } from './routes/email-outreach'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as IndexRouteImport } from './routes/index'

const SheetsSyncRoute = SheetsSyncRouteImport.update({
  id: '/sheets-sync',
  path: '/sheets-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeVaultRoute = ResumeVaultRouteImport.update({
  id: '/resume-vault',
  path: '/resume-vault',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailOutreachRoute = EmailOutreachRouteImport.update({
  id: '/email-outreach',
  path: '/email-outreach',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/email-outreach': typeof EmailOutreachRoute
  '/jobs': typeof JobsRoute
  '/profile': typeof ProfileRoute
  '/resume-vault': typeof ResumeVaultRoute
  '/settings': typeof SettingsRoute
  '/sheets-sync': typeof SheetsSyncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/email-outreach': typeof EmailOutreachRoute
  '/jobs': typeof JobsRoute
  '/profile': typeof ProfileRoute
  '/resume-vault': typeof ResumeVaultRoute
  '/settings': typeof SettingsRoute
  '/sheets-sync': typeof SheetsSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/email-outreach': typeof EmailOutreachRoute
  '/jobs': typeof JobsRoute
  '/profile': typeof ProfileRoute
  '/resume-vault': typeof ResumeVaultRoute
  '/settings': typeof SettingsRoute
  '/sheets-sync': typeof SheetsSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/applications'
    | '/email-outreach'
    | '/jobs'
    | '/profile'
    | '/resume-vault'
    | '/settings'
    | '/sheets-sync'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/applications'
    | '/email-outreach'
    | '/jobs'
    | '/profile'
    | '/resume-vault'
    | '/settings'
    | '/sheets-sync'
  id:
    | '__root__'
    | '/'
    | '/applications'
    | '/email-outreach'
    | '/jobs'
    | '/profile'
    | '/resume-vault'
    | '/settings'
    | '/sheets-sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplicationsRoute: typeof ApplicationsRoute
  EmailOutreachRoute: typeof EmailOutreachRoute
  JobsRoute: typeof JobsRoute
  ProfileRoute: typeof ProfileRoute
  ResumeVaultRoute: typeof ResumeVaultRoute
  SettingsRoute: typeof SettingsRoute
  SheetsSyncRoute: typeof SheetsSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sheets-sync': {
      id: '/sheets-sync'
      path: '/sheets-sync'
      fullPath: '/sheets-sync'
      preLoaderRoute: typeof SheetsSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume-vault': {
      id: '/resume-vault'
      path: '/resume-vault'
      fullPath: '/resume-vault'
      preLoaderRoute: typeof ResumeVaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-outreach': {
      id: '/email-outreach'
      path: '/email-outreach'
      fullPath: '/email-outreach'
      preLoaderRoute: typeof EmailOutreachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplicationsRoute: ApplicationsRoute,
  EmailOutreachRoute: EmailOutreachRoute,
  JobsRoute: JobsRoute,
  ProfileRoute: ProfileRoute,
  ResumeVaultRoute: ResumeVaultRoute,
  SettingsRoute: SettingsRoute,
  SheetsSyncRoute: SheetsSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
